version: 0.2
phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - rm -rf deploy
      - mkdir -p deploy
      - JAR=$(ls -1 build/libs/*.jar | grep -v plain | head -n 1)
      - cp "$JAR" deploy/application.jar
artifacts:
  base-directory: deploy
  files:
    - application.jar