version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - rm -rf deploy
      - mkdir -p deploy
      - cp build/libs/*.jar deploy/application.jar
      - |
        cat > deploy/Procfile <<'EOF'
        web: java -jar application.jar
        EOF

artifacts:
  base-directory: deploy
  files:
    - application.jar
    - Procfile