version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - mkdir -p deploy
      - cp build/libs/*.jar deploy/application.jar
      - printf 'web: java -jar application.jar\n' > deploy/Procfile

artifacts:
  base-directory: deploy
  files:
    - application.jar
    - Procfile