version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - rm -rf deploy
      - mkdir -p deploy
      - ls -al build/libs
      - cp build/libs/*.jar deploy/application.jar
      - echo "web: java -jar application.jar" > deploy/Procfile

artifacts:
  base-directory: deploy
  files:
    - application.jar
    - Procfile